<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226115522 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE artista (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, nacionalidad VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE artista_vinilo (artista_id INT NOT NULL, vinilo_id INT NOT NULL, PRIMARY KEY (artista_id, vinilo_id))');
        $this->addSql('CREATE INDEX IDX_AE1A8A45AEB0CF13 ON artista_vinilo (artista_id)');
        $this->addSql('CREATE INDEX IDX_AE1A8A45F8E11D70 ON artista_vinilo (vinilo_id)');
        $this->addSql('CREATE TABLE carrito (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente (carrito_id INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F41C9B25DE2CF6E7 ON cliente (carrito_id)');
        $this->addSql('CREATE TABLE detalle_carrito (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad INT NOT NULL, precio DOUBLE PRECISION NOT NULL, vinilo_id INT NOT NULL, carrito_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F38507DF8E11D70 ON detalle_carrito (vinilo_id)');
        $this->addSql('CREATE INDEX IDX_3F38507DDE2CF6E7 ON detalle_carrito (carrito_id)');
        $this->addSql('CREATE TABLE detalle_pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad INT NOT NULL, precio DOUBLE PRECISION NOT NULL, vinilo_id INT NOT NULL, pedido_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A834F569F8E11D70 ON detalle_pedido (vinilo_id)');
        $this->addSql('CREATE INDEX IDX_A834F5694854653A ON detalle_pedido (pedido_id)');
        $this->addSql('CREATE TABLE genero (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE genero_vinilo (genero_id INT NOT NULL, vinilo_id INT NOT NULL, PRIMARY KEY (genero_id, vinilo_id))');
        $this->addSql('CREATE INDEX IDX_3A89E091BCE7B795 ON genero_vinilo (genero_id)');
        $this->addSql('CREATE INDEX IDX_3A89E091F8E11D70 ON genero_vinilo (vinilo_id)');
        $this->addSql('CREATE TABLE pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total DOUBLE PRECISION NOT NULL, cliente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4EC16CEDE734E51 ON pedido (cliente_id)');
        $this->addSql('CREATE TABLE usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(255) DEFAULT NULL, direccion VARCHAR(255) DEFAULT NULL, telefono INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delete_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tipo VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON usuario (email)');
        $this->addSql('CREATE TABLE vinilo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, fecha_lanzamiento DATE NOT NULL, precio DOUBLE PRECISION NOT NULL, stock INT NOT NULL, discogs_id INT DEFAULT NULL, imagen VARCHAR(255) DEFAULT NULL, es_novedad BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE admin ADD CONSTRAINT FK_880E0D76BF396750 FOREIGN KEY (id) REFERENCES usuario (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artista_vinilo ADD CONSTRAINT FK_AE1A8A45AEB0CF13 FOREIGN KEY (artista_id) REFERENCES artista (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE artista_vinilo ADD CONSTRAINT FK_AE1A8A45F8E11D70 FOREIGN KEY (vinilo_id) REFERENCES vinilo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B25DE2CF6E7 FOREIGN KEY (carrito_id) REFERENCES carrito (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cliente ADD CONSTRAINT FK_F41C9B25BF396750 FOREIGN KEY (id) REFERENCES usuario (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE detalle_carrito ADD CONSTRAINT FK_3F38507DF8E11D70 FOREIGN KEY (vinilo_id) REFERENCES vinilo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE detalle_carrito ADD CONSTRAINT FK_3F38507DDE2CF6E7 FOREIGN KEY (carrito_id) REFERENCES carrito (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F569F8E11D70 FOREIGN KEY (vinilo_id) REFERENCES vinilo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE detalle_pedido ADD CONSTRAINT FK_A834F5694854653A FOREIGN KEY (pedido_id) REFERENCES pedido (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE genero_vinilo ADD CONSTRAINT FK_3A89E091BCE7B795 FOREIGN KEY (genero_id) REFERENCES genero (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE genero_vinilo ADD CONSTRAINT FK_3A89E091F8E11D70 FOREIGN KEY (vinilo_id) REFERENCES vinilo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pedido ADD CONSTRAINT FK_C4EC16CEDE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE admin DROP CONSTRAINT FK_880E0D76BF396750');
        $this->addSql('ALTER TABLE artista_vinilo DROP CONSTRAINT FK_AE1A8A45AEB0CF13');
        $this->addSql('ALTER TABLE artista_vinilo DROP CONSTRAINT FK_AE1A8A45F8E11D70');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B25DE2CF6E7');
        $this->addSql('ALTER TABLE cliente DROP CONSTRAINT FK_F41C9B25BF396750');
        $this->addSql('ALTER TABLE detalle_carrito DROP CONSTRAINT FK_3F38507DF8E11D70');
        $this->addSql('ALTER TABLE detalle_carrito DROP CONSTRAINT FK_3F38507DDE2CF6E7');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F569F8E11D70');
        $this->addSql('ALTER TABLE detalle_pedido DROP CONSTRAINT FK_A834F5694854653A');
        $this->addSql('ALTER TABLE genero_vinilo DROP CONSTRAINT FK_3A89E091BCE7B795');
        $this->addSql('ALTER TABLE genero_vinilo DROP CONSTRAINT FK_3A89E091F8E11D70');
        $this->addSql('ALTER TABLE pedido DROP CONSTRAINT FK_C4EC16CEDE734E51');
        $this->addSql('DROP TABLE admin');
        $this->addSql('DROP TABLE artista');
        $this->addSql('DROP TABLE artista_vinilo');
        $this->addSql('DROP TABLE carrito');
        $this->addSql('DROP TABLE cliente');
        $this->addSql('DROP TABLE detalle_carrito');
        $this->addSql('DROP TABLE detalle_pedido');
        $this->addSql('DROP TABLE genero');
        $this->addSql('DROP TABLE genero_vinilo');
        $this->addSql('DROP TABLE pedido');
        $this->addSql('DROP TABLE usuario');
        $this->addSql('DROP TABLE vinilo');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
