<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260227124155 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cliente ALTER carrito_id DROP NOT NULL');
        $this->addSql('DROP INDEX favorito_usuario_id_vinilo_id_key');
        $this->addSql('ALTER TABLE favorito ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE favorito ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE favorito ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE favorito ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE usuario ALTER nombre DROP NOT NULL');
        $this->addSql('ALTER TABLE usuario ALTER direccion DROP NOT NULL');
        $this->addSql('ALTER TABLE vinilo ALTER fecha_lanzamiento DROP NOT NULL');
        $this->addSql('ALTER TABLE vinilo ALTER es_novedad SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cliente ALTER carrito_id SET NOT NULL');
        $this->addSql('ALTER TABLE favorito ALTER id SET DEFAULT nextval(\'favorito_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE favorito ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE favorito ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE favorito ALTER created_at DROP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX favorito_usuario_id_vinilo_id_key ON favorito (usuario_id, vinilo_id)');
        $this->addSql('ALTER TABLE usuario ALTER nombre SET NOT NULL');
        $this->addSql('ALTER TABLE usuario ALTER direccion SET NOT NULL');
        $this->addSql('ALTER TABLE vinilo ALTER fecha_lanzamiento SET NOT NULL');
        $this->addSql('ALTER TABLE vinilo ALTER es_novedad DROP NOT NULL');
    }
}
